name: Flutter Integration Tests on iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Ruby for CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: List simulators
        run: xcrun simctl list

      - name: Start iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Cgit statusontents/Developer
          sudo xcodebuild -runFirstLaunch
          sudo xcrun simctl boot "iPhone 11"
        continue-on-error: true

      - name: Run integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_tests/tests/add_to_favorites_test.dart -d "iPhone 11"
        env:
          DISPLAY: ":0"