name: Flutter Integration Test (iOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'

    - name: Install Dart
      run: |
        brew tap dart-lang/dart
        brew install dart
        dart --version

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup

    - name: Install dependencies
      run: flutter pub get

    - name: Build for iOS
      run: flutter build ios --no-codesign

    - name: Run integration tests
      run: |
        flutter drive \
          --driver=test_driver/integration_test.dart \
          --target=integration_tests/tests/add_to_favorites_test.dart \
          -d 'iPhone 12'

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: build/ios/Build/Products/Debug-iphonesimulator/