name: Flutter Integration Tests on iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Ruby for CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: Start iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch
          sudo xcrun simctl boot "iPhone 15"
        continue-on-error: true

      - name: Run integration tests
        run: flutter drive --target=test_driver/app_test.dart -d "iPhone 15"