name: Flutter Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'  # Specify the Flutter version explicitly

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '>=2.18.1 <3.0.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Run integration tests
      run: |
        mkdir -p test-reports
        flutter test integration_tests/tests/add_to_favorites_test.dart --reporter json > test-reports/report.json
        cat test-reports/report.json | flutter pub run testreport:tojunit --output test-reports/report.xml

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-reports/report.xml