name: Flutter Integration Test on iOS

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'  # Specify a known working Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept
        sudo gem install cocoapods

    - name: Create directories for screenshots and reports
      run: |
        mkdir -p test/screenshots
        mkdir -p test/reports

    - name: Build iOS app for testing
      run: flutter build ios --debug --no-codesign

    - name: Start iPhone simulator
      run: |
        export SIMULATOR_UDID=$(xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-14)
        xcrun simctl boot $SIMULATOR_UDID
        xcrun simctl bootstatus $SIMULATOR_UDID

    - name: Install app on simulator
      run: flutter install --device-id $SIMULATOR_UDID

    - name: Run integration tests
      run: flutter drive --target=test_driver/app.dart --device-id $SIMULATOR_UDID --machine > test/reports/integration_test_results.json

    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-screenshots
        path: test/screenshots

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test/reports
